[workspace]
channels = ["conda-forge", "main", "r", "msys2"]
name = "pripy3"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
python = ">=3.9"
pytorch-cpu = ">=2.5.1,<3"
numpy = ">=2.2.4,<3"
networkx = ">=3.4.2,<4"
cvxpy = ">=1.6.5,<2"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.1,<4"
